### Registrar comida (requiere token JWT con rol ADMIN)
POST {{host}}/{{prefix}}/food-log/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "pizza",
  "calories": 330,
  "notes": "Desayuno completo con café"
}

### Obtener todos los registros (paginados)
GET {{host}}/{{prefix}}/food-log/list?page=1&limit=10
Authorization: Bearer {{token}}


### Buscar comidas por nombre
GET {{host}}/{{prefix}}/food-log/search?filter=carne&page=1&limit=10
Authorization: Bearer {{token}}


### Actualizar registro
PATCH {{host}}/{{prefix}}/food-log/dae95df9-c7c8-4015-84c6-f49afffdb177
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Pollo a la plancha",
  "calories": 450,
  "notes": "Cena post entreno"
}

### Eliminar registro
DELETE {{host}}/{{prefix}}/food-log/c3f30ea1-9931-4074-a021-f04461813473
Authorization: Bearer {{token}}